version: "2"

########################################################################################################################
#
# TOC
#
########################################################################################################################
#
# 1. BUILD
#
########################################################################################################################

tasks:
  ######################################################################################################################
  #
  #  1. BUILD
  #
  ######################################################################################################################

  d:build:debian:
    desc: Build a PHP Debian-based Docker image
    cmds:
      - task: d:build
        vars:
          TYPE: debian
          TARGET: '{{.TARGET | default "builder"}}'
          TAG_VERSION: '{{.TAG_VERSION | default "latest"}}'

  d:build:alpine:
    desc: Build a PHP Alpine-based Docker image
    cmds:
      - task: d:build
        vars:
          TYPE: alpine
          TARGET: '{{.TARGET | default "builder"}}'
          TAG_VERSION: '{{.TAG_VERSION | default "latest"}}'

  d:build:
    silent: true
    deps:
      - task: d:lint
        vars:
          TYPE: '{{.TYPE}}'
    preconditions:
      - sh: test '{{.TYPE}}' != '<no value>'
        msg: TYPE needs to contain the Docker OS TYPE [alpine, debian]
      - sh: test '{{.TARGET}}' != '<no value>'
        msg: TARGET needs to contain the Docker TARGET [runtime, builder]
      - sh: test '{{.TAG_VERSION}}' != '<no value>'
        msg: TAG_VERSION needs to contain the tag that will be assigned to the Docker build
    env:
      DOCKER_BUILDKIT: 1
    cmds:
      - docker build
        --target {{.TARGET}}
        --tag {{.TAG_REPOSITORY}}/{{.TAG_NAME}}:{{.TAG_VERSION}}-{{.TARGET}}-{{.TYPE}}
        ./{{.TYPE}}

  d:lint:
    desc: Apply a Dockerfile linter (https://github.com/hadolint/hadolint)
    silent: true
    preconditions:
      - sh: test '{{.TYPE}}' != '<no value>'
        msg: TYPE needs to contain the Docker OS TYPE [alpine, debian]
    cmds:
      - docker run
        --interactive
        --rm
        hadolint/hadolint:{{.HADOLINT_TAG_VERSION}}
        hadolint
        --ignore DL3018
        --ignore DL3008
        -
        < ./{{.TYPE}}/Dockerfile

