name: Build latest Alpine images

on:
  push:
    branches: [master]
    paths: ['alpine/**']

env:
  OS: alpine
  DOCKER_REPO: ilyes512/php73-php

jobs:
  build_latest_alpine:
    name: Build latest Alpine
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker registry
        uses: azure/docker-login@8d6f807dfe933ef49956873df1022dd03a761071
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build containers
        run: |
          docker build --tag $DOCKER_REPO:$OS-latest-builder --target builder ./$OS
          docker build --tag $DOCKER_REPO:$OS-latest-runtime --target runtime ./$OS
      - name: Tag latest
        run: |
          docker tag $DOCKER_REPO:$OS-latest-builder $DOCKER_REPO:latest-builder
          docker tag $DOCKER_REPO:$OS-latest-runtime $DOCKER_REPO:latest-runtime
      - name: Push containers
        run: |
          docker push $DOCKER_REPO:$OS-latest-builder
          docker push $DOCKER_REPO:$OS-latest-runtime
          docker push $DOCKER_REPO:$latest-builder
          docker push $DOCKER_REPO:latest-runtime
